### ISSUE TITLE
Add facilities for scheduled debates & tracking statistics

### ISSUE THREAD

**Issue by julianmichael** [julianmichael/debate#4]
We want to create a smooth process for running debates each week. This means the following:
- [x] Keep track of the users (debaters etc.) on the server.
- [x] Add facilities for setting up debates (with source material, etc.) where users are assigned particular roles.
- [x] Make it so when a user enters such a debate, their role is fixed.

This is the most impactful thing to get done soon so we can start storing the results of our debates.

Creating a separate issue for the leaderboard.

**Comment by julianmichael** [comment]
Closed as of [here](https://github.com/julianmichael/debate/commit/f381468e53be454d41783d17f09e25a9423add23).
